import * as Mailgen from 'mailgen';
import * as nodemailer from 'nodemailer';
import * as mailgunTransport from 'nodemailer-mailgun-transport';
import * as sendmailTransport from 'nodemailer-sendmail-transport';

import * as colors from 'shared/colors';

function createTransport() {
  if (process.env.MAILGUN_API_KEY) {
    return mailgunTransport({
      auth: {
        api_key: process.env.MAILGUN_API_KEY,
        domain: 'hackcambridge.com',
      },
    });
  }

  // We have no real mailing transports to use
  // Fallback to sendmail
  return sendmailTransport();
}

const transporter = nodemailer.createTransport(createTransport());
const mailGenerator = new Mailgen({
  theme: 'default',
  product: {
    name: 'Hack Cambridge',
    link: 'https://hackcambridge.com',
  },
});

export function makeInstruction({ instructions, button: { link, text }}) {
  return {
    instructions,
    button: {
      link,
      text,
      color: colors.PRIMARY_COLOR,
    },
  };
}

/**
 * Send an email
 *
 * Contents of the email are generated by Mailgen. See their docs for valid inputs
 * https://www.npmjs.com/package/mailgen
 */
export function sendEmail({ to, contents }) {
  return new Promise((resolve, reject) => {
    transporter.sendMail({
      from: '"Hack Cambridge" <team@hackcambridge.com>',
      to,
      subject: contents.subject,
      text: mailGenerator.generatePlaintext(contents),
      html: mailGenerator.generate(contents),
    }, (error, info) => {
      if (error) {
        console.log('Error sending email', error);
        reject(error);
        return;
      }

      resolve(info);
    });
  });
}
