const nodemailer = require('nodemailer');
const sendmailTransport = require('nodemailer-sendmail-transport');
const mailgunTransport = require('nodemailer-mailgun-transport');
const Mailgen = require('mailgen');

function createTransport() {
  if (process.env.MAILGUN_API_KEY) {
    return mailgunTransport({
      auth: {
        api_key: process.env.MAILGUN_API_KEY,
        domain: 'hackcambridge.com',
      },
    });
  }

  // We have no real mailing transports to use
  // Fallback to sendmail
  return sendmailTransport();
}

const transporter = nodemailer.createTransport(createTransport());
const mailGenerator = new Mailgen({
  theme: 'default',
  product: {
    name: 'Hack Cambridge',
    link: 'https://hackcambridge.com',
  },
});

/**
 * Send an email
 * 
 * Contents of the email are generated by Mailgen. See their docs for valid inputs
 * https://www.npmjs.com/package/mailgen
 */
exports.sendEmail = function sendEmail({ to, contents }) {
  return new Promise((resolve, reject) => {
    transporter.sendMail({
      from: '"Hack Cambridge" <team@hackcambridge.com>',
      to,
      subject: contents.subject,
      text: mailGenerator.generatePlaintext(contents),
      html: mailGenerator.generate(contents),
    }, (error, info) => {
      if (error) {
        reject(error);
        return;
      }

      resolve(info);
    });
  });
}

exports.templates = {
  applied: require('./applied'),
};
